### ISSUE TITLE
Midterm part 1 midterm-if.py ready for grading

### ISSUE THREAD

**Issue by iimckenney-matc** [madisoncollege-it-programs/python-scripting-iimckenney-matc#10]

**Comment by cethenmc** [comment]
Nice job getting to the bottom of this.  I like that you analyzed your data carefully to identify the column structure in the flat file.  This one is tough because I really feel like I should take 1 to 2 points off, but you did everything that was required on the assignment (including extracting the line number and casting the string to an int).  As a result your score is 33/33.
