### ISSUE TITLE
Week 9 Functions lab f2c.py and tempconversion.py ready for grading

### ISSUE THREAD

**Issue by iimckenney-matc** [madisoncollege-it-programs/python-scripting-iimckenney-matc#12]

**Comment by cethenmc** [comment]
Well done!  Please put the author and description in each script every time.  Even though this time the lab only asked for the first.  Thanks!

**Comment by cethenmc** [comment]
I will also add that the tempconversion.py was intended to be run through the "main()" function, which is why the part title looks like this:  "Script 2 - Temp Conversion (**Main**)."  It was not super clear, so I am not deducting points.  However, you may want to consider modifying your tempconversion.py script to run that way.
